import { media } from './media';

export const reassuranceStats = [
  { label: 'Sunday Services', value: '8:00, 9:30, 11:00, 12:30' },
  { label: 'First Wednesday', value: '7:00 PM' },
  { label: 'Location', value: '400 Northview Rd' },
  { label: 'City', value: 'Nixa, MO' }
];

export const values = [
  {
    title: 'Influence',
    description: 'We do not pursue popularity; we pursue impact. This starts by reflecting Jesus in everything we do.'
  },
  {
    title: 'Generosity',
    description: 'We give on purpose, for a purpose. We are called to build His Kingdom, not just consume from it.'
  },
  {
    title: 'Unity',
    description: 'One mission, one vision, one team. We move forward together.'
  },
  {
    title: 'Excellence',
    description: 'Details matter. How we do something holds the same value as why we do something.'
  },
  {
    title: 'Honor',
    description: 'We revere God and value people. This is not about status.'
  },
  {
    title: 'Faith',
    description: 'We have faith in God, faith in people, and faith for miracles. We pray big and believe God is moving.'
  },
  {
    title: 'Fun',
    description: 'We enjoy serving Jesus and bring energy, joy, and passion to ministry.'
  },
  {
    title: 'Multiplication',
    description: 'Maintaining is the fruit of the world; multiplication is the fruit of the Kingdom of God.'
  }
];

export const beliefs = [
  {
    heading: 'The Bible Map',
    text: 'The Holy Bible is the authoritative Word of God. It alone is the final authority in determining all doctrinal truths. In its original writing, it is inspired, infallible and inerrant (2 Timothy 3:16; 2 Peter 1:20-21; Proverbs 30:5; Romans 16:25-26).'
  },
  {
    heading: 'Holy Trinity',
    text: 'There is one God, eternally existent in three persons: Father, Son and Holy Spirit. These three are co-equal and co-eternal (I John 5:7; Genesis 1:26; Matthew 3:16-17, 28:19; Luke 1:35; Isaiah 9:6; Hebrews 3:7-11).'
  },
  {
    heading: 'Repentance in the Bible',
    text: 'Repentance is the commitment to turn away from sin in every area of our lives and to follow Christ, which allows us to receive His redemption and to be regenerated by the Holy Spirit. Thus, through repentance we receive forgiveness of sins and appropriate salvation (Acts 2:21, 3:19; 1 John 1:9).'
  },
  {
    heading: 'Salvation',
    text: 'We are saved by grace through faith in Jesus Christ; His death, burial, and resurrection. Salvation is a gift from God, not a result of our good works or of any human efforts (Ephesians 2:8-9; Galatians 2:16, 3:8; Titus 3:5; Romans 10:9-10; Acts 16:31; Hebrews 9:22).'
  },
  {
    heading: 'Baptism in the Holy Spirit',
    text: 'Given at Pentecost, it is the promise of the Father, sent by Jesus after His Ascension, to empower the church to preach the Gospel throughout the whole earth (Joel 2:28-29; Matthew 3:11; Mark 16:17; Acts 1:5, 2:1-4, 17, 38-39, 8:14-17, 10:38, 44-47, 11:15-17, 19:1-6).'
  },
  {
    heading: 'Sanctification Process',
    text: 'Sanctification is the ongoing process of yielding to God’s Word and His Spirit in order to complete the development of Christ’s character in us. It is through the present ministry of the Holy Spirit and the Word of God that the Christian is enabled to live a godly life (Thessalonians 4:3, 5:23; 2 Corinthians 3:18, 6:14-18, 2 Thessalonians 2:1-3, Romans 8:29, 12:1-2, Hebrews 2:11).'
  }
];

export const staff = [
  {
    name: 'Stone Moss',
    role: 'Lead Pastor',
    bio: 'Stone leads with bold faith, big vision, and a heart to see Nixa transformed by the power of Jesus.',
    image: media.staff.stone,
    team: 'Executive'
  },
  {
    name: 'Brian Smith',
    role: 'Executive Pastor',
    bio: 'Brian serves on the executive leadership team and helps lead mission and ministry operations.',
    image: media.staff.operations,
    team: 'Executive'
  },
  {
    name: 'Meagan Cook',
    role: 'Executive Director',
    bio: 'Meagan helps guide church-wide ministry execution and team development.',
    image: media.staff.kids,
    team: 'Executive'
  },
  {
    name: 'Jill Bryant',
    role: 'Worship Director',
    bio: 'Jill leads worship ministry and helps create space for people to encounter God.',
    image: media.staff.worship,
    team: 'Ministry'
  },
  {
    name: 'Emily Smith',
    role: 'Small Groups Pastor',
    bio: 'Emily leads groups ministry and helps people build real relationships in community.',
    image: media.staff.groups,
    team: 'Discipleship'
  },
  {
    name: 'Eli Strong',
    role: 'YTH Pastor',
    bio: 'Eli leads Limitless YTH and serves middle and high school students each week.',
    image: media.staff.youth,
    team: 'Family'
  },
  {
    name: 'Dennis Acox',
    role: 'Operations Director',
    bio: 'Dennis helps steward day-to-day operations that support weekend and midweek ministry.',
    image: media.staff.care,
    team: 'Operations'
  }
];

export const testimonials = [
  {
    quote: 'A common thing we hear from parents is that their kids are excited to come back each week.',
    name: 'Often Shared by Families'
  },
  {
    quote: 'Many people tell us groups helped them build real relationships and feel less alone.',
    name: 'Often Shared in Groups'
  },
  {
    quote: 'We often hear that care and prayer support helped people through hard seasons.',
    name: 'Often Shared in Care'
  }
];

export const messages = [
  {
    title: 'The Problem With Potential',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'Joseph',
    duration: 'On YouTube',
    summary: 'Part of the Joseph series focused on trusting God with your next step.',
    image: media.messages.problemPotential,
    featured: true
  },
  {
    title: 'This Wasn’t My Plan',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'Joseph',
    duration: 'On YouTube',
    summary: 'A Joseph series message about trusting God when life does not go as expected.',
    image: media.messages.thoughtOver
  },
  {
    title: 'You Thought It Was Over',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'Easter Sunday',
    duration: 'On YouTube',
    summary: 'An Easter message about hope and new life through Jesus.',
    image: media.messages.anxious
  },
  {
    title: 'Why You\'re So Anxious',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'The Way Of Jesus',
    duration: 'On YouTube',
    summary: 'From The Way Of Jesus series, this message points to peace in Christ.',
    image: media.messages.controlsLife
  },
  {
    title: 'The Jesus You Wanted vs. The Jesus You Need',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'The Way Of Jesus',
    duration: 'On YouTube',
    summary: 'A message on following Jesus as He is, not as we prefer Him to be.',
    image: media.messages.choicesShape
  },
  {
    title: 'All For The One',
    speaker: 'Pastor Stone Moss',
    date: 'Recent Sunday',
    series: 'The Way Of Jesus',
    duration: 'On YouTube',
    summary: 'A call to live on mission and carry the heart of Jesus toward people.',
    image: media.messages.ambassadors
  }
];

export const events = [
  {
    title: 'First Wednesday Service',
    date: 'First Wednesday of each month',
    time: '7:00 PM',
    location: 'Limitless Church',
    category: 'Worship',
    description: 'Join us for a midweek service of worship and time in the Word.',
    image: media.events.worshipNight,
    featured: true
  },
  {
    title: 'Baptism',
    date: 'Upcoming Sunday',
    time: 'During Sunday services',
    location: 'Limitless Church',
    category: 'Next Step',
    description: 'Baptism is a public declaration of faith in Jesus and a next step after choosing to follow Him.',
    image: media.events.serveRally
  },
  {
    title: 'Child Dedication',
    date: 'Upcoming Sunday',
    time: 'During Sunday services',
    location: 'Limitless Church',
    category: 'Family',
    description: 'A meaningful moment where parents dedicate their child in faith with support from church family.',
    image: media.events.childDedication
  },
  {
    title: 'New Here Party',
    date: 'First Sunday of each month',
    time: '5:00 PM',
    location: 'Limitless Church',
    category: 'Next Step',
    description: 'Learn the mission and vision of Limitless, meet the lead team, and explore how to begin serving.',
    image: media.events.newHereLunch
  },
  {
    title: 'Limitless YTH',
    date: 'Wednesdays',
    time: '7:00 PM (Doors open at 6:30 PM)',
    location: 'Limitless Church',
    category: 'Youth',
    description: 'Weekly youth service for 6th-12th graders to grow in faith and build real friendships.',
    image: media.events.studentsKickoff
  },
  {
    title: 'Small Groups',
    date: 'Ongoing',
    time: 'Various days and times',
    location: 'Nixa area',
    category: 'Groups',
    description: 'Groups are where relationships are built, faith is strengthened, and life is shared together.',
    image: media.events.prayerCare
  }
];

export const ministries = [
  {
    title: 'Limitless Kids',
    audience: 'Infants through 5th grade',
    description: 'Age-specific classes with secure check-in, fun worship, and engaging Bible teaching.',
    image: media.ministries.kids
  },
  {
    title: 'Limitless YTH',
    audience: '6th-12th grade | Wednesdays at 7:00 PM',
    description: 'A weekly youth gathering where students connect, worship, and grow in faith.',
    image: media.ministries.students
  },
  {
    title: 'Small Groups',
    audience: 'Adults in every stage of life',
    description: 'Find a group where you can connect, grow, and be encouraged in everyday life.',
    image: media.ministries.groups
  },
  {
    title: 'Care Team',
    audience: 'Anyone needing support',
    description: 'Prayer, encouragement, and pastoral support for both celebrations and hard seasons.',
    image: media.ministries.carePrayer
  }
];

export const kidsAgeGroups = [
  {
    stage: 'Nursery',
    age: 'Infants + Toddlers',
    detail: 'Loving care in a secure check-in/check-out environment designed for your youngest kids.'
  },
  {
    stage: 'Preschool',
    age: 'Early Childhood',
    detail: 'Fun worship, engaging Bible stories, and activities built for early learning stages.'
  },
  {
    stage: 'Elementary',
    age: 'Kindergarten through 5th grade',
    detail: 'Age-specific teaching and small-group connection that helps kids know God and love people.'
  }
];

export const careResources = [
  {
    title: 'Prayer Team',
    summary: 'Receive prayer, encouragement, and spiritual support through in-person meetings or phone calls.'
  },
  {
    title: 'Marriage Mentoring',
    summary: 'Support for marriages through biblical guidance, practical encouragement, and prayer.'
  },
  {
    title: 'Premarital Coaches',
    summary: 'Coaching for engaged couples preparing for a strong, Christ-centered marriage.'
  },
  {
    title: 'Local Care Resources',
    summary: 'Connections to local counseling, crisis intervention, addiction recovery, and assistance resources.'
  }
];

export const nextSteps = [
  {
    title: 'New Here Party',
    description: 'Join us the first Sunday of every month at 5:00 PM to learn our mission and meet the team.',
    cta: 'RSVP'
  },
  {
    title: 'Plan A Visit',
    description: 'Join us this Sunday and experience worship, practical teaching, and community in Nixa.',
    cta: 'Plan Your Visit'
  },
  {
    title: 'Join A Small Group',
    description: 'Groups are where relationships are built, faith is strengthened, and life is shared together.',
    cta: 'Browse Groups'
  },
  {
    title: 'Water Baptism',
    description: 'Take your next step by publicly declaring your faith in Jesus through baptism.',
    cta: 'Register For Baptism'
  },
  {
    title: 'Join A Serve Team',
    description: 'Find out how to begin serving and helping people encounter God each week.',
    cta: 'Start Serving'
  }
];

export const visitFaqs = [
  {
    question: 'What should I wear?',
    answer: 'Come as you are. You will see people dressed casual to dressy. We want you to feel comfortable.'
  },
  {
    question: 'How long is a service?',
    answer: 'You can expect passionate worship and a practical, Bible-based message for real life.'
  },
  {
    question: 'Where do I park?',
    answer: 'Guest parking is marked near the main entrance, and our team is outside to help you find your way.'
  },
  {
    question: 'Is there something for my kids?',
    answer: 'Yes. Limitless Kids has safe, age-based environments from nursery through elementary every Sunday.'
  },
  {
    question: 'Can I watch online first?',
    answer: 'Yes. You can watch recent messages on YouTube to get a feel for our teaching.'
  }
];

export const giveFaqs = [
  {
    question: 'Are donations tax exempt?',
    answer: 'Yes. Limitless Church has official non-profit status, and donations are tax deductible.'
  },
  {
    question: 'Will I receive a giving statement?',
    answer: 'Yes. Donors receive an annual giving statement with total contributions.'
  },
  {
    question: 'What will my giving be used for?',
    answer: 'Giving supports the mission of Limitless Church and helps fund ministry, outreach, and discipleship.'
  },
  {
    question: 'How much can I give?',
    answer: 'You can give any amount, whether it is a tithe, offering, or one-time gift.'
  },
  {
    question: 'Can I set up recurring giving?',
    answer: 'Yes. Recurring giving is available through the online giving flow.'
  }
];

export const careFaqs = [
  {
    question: 'What kind of support does the care team offer?',
    answer: 'Our care team provides prayer, encouragement, and spiritual guidance for many seasons of life.'
  },
  {
    question: 'Do you offer marriage support?',
    answer: 'Yes. Marriage mentoring and premarital coaching are available through the care ministry.'
  },
  {
    question: 'Do you share local counseling or crisis resources?',
    answer: 'Yes. We can connect you with local counseling, crisis intervention, recovery, and assistance resources.'
  }
];

export const impactHighlights = [
  {
    title: 'Life-Changing Ministry',
    text: 'Every gift supports weekend ministry and discipleship for people in every stage of life.'
  },
  {
    title: 'Community Outreach',
    text: 'Generosity helps local outreach efforts that serve practical needs in our community.'
  },
  {
    title: 'Kingdom Impact',
    text: 'Giving helps advance the mission to help people encounter God, love people, and find purpose.'
  }
];
